# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- task: apimfunction@3
  inputs:
    ConnectedServiceNameARM: 'APIM-Functions-Connection'
    APIResourceGroupName: 'apim-demo'
    ApiPortalName: 'https://my-api-management-service.portal.azure-api.net/'
    targetapi: 'my-demo-function-02'
    pathapi: 'my-demo-function-02'
    ResourceGroupName: 'apim-demo'
    HostingWebSite: 'my-demo-function-02'